// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuthorizationCode struct {
	ID          uuid.UUID    `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	ClientID    uuid.UUID    `json:"client_id"`
	Code        string       `json:"code"`
	RedirectUri string       `json:"redirect_uri"`
	CreatedAt   sql.NullTime `json:"created_at"`
	ExpiresAt   time.Time    `json:"expires_at"`
	IsUsed      sql.NullBool `json:"is_used"`
}

type Client struct {
	ID             uuid.UUID      `json:"id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	ClientID       string         `json:"client_id"`
	ClientSecret   string         `json:"client_secret"`
	RedirectUris   []string       `json:"redirect_uris"`
	WebsiteUrl     sql.NullString `json:"website_url"`
	IsActive       sql.NullBool   `json:"is_active"`
	IsConfidential sql.NullBool   `json:"is_confidential"`
	CreatedBy      uuid.NullUUID  `json:"created_by"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	ClientID  uuid.UUID    `json:"client_id"`
	Token     string       `json:"token"`
	CreatedAt sql.NullTime `json:"created_at"`
	ExpiresAt time.Time    `json:"expires_at"`
	IsActive  sql.NullBool `json:"is_active"`
}

type Session struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	SessionToken string         `json:"session_token"`
	UserAgent    sql.NullString `json:"user_agent"`
	IpAddress    sql.NullString `json:"ip_address"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	ExpiresAt    time.Time      `json:"expires_at"`
	IsActive     sql.NullBool   `json:"is_active"`
}

type User struct {
	ID            uuid.UUID    `json:"id"`
	Email         string       `json:"email"`
	PasswordHash  string       `json:"password_hash"`
	FullName      string       `json:"full_name"`
	DateOfBirth   sql.NullTime `json:"date_of_birth"`
	EmailVerified sql.NullBool `json:"email_verified"`
	Active        sql.NullBool `json:"active"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}
